// Suggested code may be subject to a license. Learn more: ~LicenseLog:2649723314.
// Suggested code may be subject to a license. Learn more: ~LicenseLog:600891746.
// Suggested code may be subject to a license. Learn more: ~LicenseLog:995478794.
// Suggested code may be subject to a license. Learn more: ~LicenseLog:2832454496.
const gulp = require('gulp');
const ts = require('gulp-typescript');
const sourcemaps = require('gulp-sourcemaps');
const babel = require('gulp-babel');
const browserify = require('browserify');
const source = require('vinyl-source-stream');
const buffer = require('vinyl-buffer');
const sass = require('gulp-sass')(require('sass'));

const tsProject = ts.createProject('tsconfig.json');

gulp.task('compile-ts', () => {
  return tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(tsProject())
    .pipe(babel({
      presets: ['@babel/preset-env', '@babel/preset-react']
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./dist'));
});

gulp.task('compile-sass', () => {
  return gulp.src('./src/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./dist'));
});


gulp.task('default', gulp.parallel('compile-ts', 'compile-sass'));

// ✨ generated by Google Gemini ✨